version: 2
jobs:
  build:
    working_directory: /esp-rs
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t esp-rs .
      - run:
          name: Test esp8266 project
          command: |
            docker run esp-rs /bin/bash -c "USER=tester ARCH=esp8266 ./build.sh testproj-esp8266"
      - run:
          name: Test esp32 project
          command: |
            docker run esp-rs /bin/bash -c "USER=tester ARCH=esp32 ./build.sh testproj-esp32"
